// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using angularSPA.Data;

#nullable disable

namespace angularSPA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("angularSPA.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Продуктовая"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Name = "Транспортная"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Name = "Благотворительная"
                        });
                });

            modelBuilder.Entity("angularSPA.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "ООО Восток"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Name = "ЗАО Север"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000003"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "ООО Продукты плюс"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000004"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Name = "ТрансЛогистик"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000005"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Name = "Фонд Помощи"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000006"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "ООО Свежий хлеб"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000007"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Name = "Автоперевозки"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000008"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Name = "Добрые руки"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000009"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "ООО Молоко"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-00000000000a"),
                            ActivityId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Name = "Быстрая доставка"
                        });
                });

            modelBuilder.Entity("angularSPA.Models.Company", b =>
                {
                    b.HasOne("angularSPA.Models.Activity", "Activity")
                        .WithMany("Companies")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("angularSPA.Models.Activity", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
